env:
  browser: true
  es6: true
  node: true
extends:
  - '@bangbang93/recommended'
  - 'plugin:vue/recommended'
plugins:
  - vue
  - '@typescript-eslint'
parserOptions:
  project: ./tsconfig.json
  parser: '@typescript-eslint/parser'
  extraFileExtensions: ['.vue']
rules:
  '@typescript-eslint/no-var-requires': 0
